#ifndef FIXEDROWTABLE_H
#define FIXEDROWTABLE_H

#include <QTableView>
#include "FixedRowTableDelegate.h"
#include "FixedRowBox.h"

namespace Commissionator {

    /**
     *  Class creates a customized QTableView with a fixed search bar, 
     *  buttons on each row, and a few minor useability tweaks.
     */
    class FixedRowTable : public QTableView {

        Q_OBJECT

    public:
        /**
         *  Constructor accepts a model for which we are to build the table.
         *
         *  @param model - Pointer to QAbstractItemModel based model on use
         *      for the proxy model and views.
         */
        FixedRowTable(QAbstractItemModel *model);

        /**
         *  Destructor cleans up internal objects.
         */
        ~FixedRowTable();

        void setBoxBottom(const bool newOnBottom);

        void setBoxText(QString newText);

        void setButtonIcon(QString newIcon);

        void setButtonActivated(const bool isEnabled);

        void setButtonSize(int size);

        /**
         *  Overrides default setColumnHidden function to call the same
         *  function with the same parameters on box as well.
         */
        void setColumnHidden(int column, bool hide);

        

    protected:
        /**
         *  Initializes connections.
         *  Exists to allow for easier use of derived classes.
         */
        void createConnections();

        /**
         *  Initializes delegate.
         *  Exists to allow for easier use of derived classes.
         */
        void createDelegate();

        /**
         *  Initializes proxy.
         *  Exists to allow for easier use of derived classes.
         */
        void createProxy();

        /**
         *  Initializes search box.
         *  Exists to allow for easier use of derived classes.
         */
        void createBox();

        /**
         *  Initializes table.
         *  Exists to allow for easier use of derived classes.
         */
        void createTable();

        /**
         *  Initializes the object and all its sub objects.
         */
        void init();

        /**
         *  Overrides the default moveCursor function so that the user can not
         *  use keyboard controls to navigate to the hidden top row.
         *
         *  @param cursorAction - the action that the function is analyzing
         *  @param modifiers - a list of keyboard modifiers that may be pressed
         *      (shift, ctrl, etc)
         *
         *  @return - the new QModelIndex generated by the function based on
         *      the current index and cursorAction
         */
        QModelIndex moveCursor(CursorAction cursorAction, Qt::KeyboardModifiers modifiers) Q_DECL_OVERRIDE;

        /**
         *  Overrides the default resizeEvent function so that in addition to
         *  its normal use, it also calls updateSearchBoxGeometry()
         * 
         *  @param event - Pointer to QResizeEvent that describes the resize.
         */
        void resizeEvent(QResizeEvent *event) Q_DECL_OVERRIDE;

        /**
         *  Overrides the default scrollTo function to prevent the user from
         *  scrolling to the hidden row.
         *
         *  @param index - index that the table is scrolling to
         *  @param hint - hint as to how the scroll should occur
         */
        void scrollTo(const QModelIndex &index, ScrollHint hint = EnsureVisible) Q_DECL_OVERRIDE;

    private:

        /**
        *  Updates the size of the search box based on the dimensions of the
        *  search table.
        */
        void updateBoxGeometry();

        //Proxy model that creates the search column and manages it
        FixedRowProxyModel *proxy;
        //Search box inherits from QTableView and provides additional functionality
        FixedRowBox *box;
        //delegate that handles the icons displayed in on the table
        FixedRowTableDelegate *delegate;
        bool boxOnBottom;

    private slots:
        /**
         *  Updates the width of the a column in the search box whenever one is
         *  changed in the search table
         *
         *  @param logicalIndex - the logical index of the column that has been
         *      changed
         *  @param oldSize - int containing the old size in number of pixels
         *  @param newSize - int containing the new size in number of pixels
         */
        void updateSectionWidth(int logicalIndex, int oldSize, int newSize);

        /**
         *  Updates the height of the row the search box is in whenever the
         *  matching one is changed in the search table
         *
         *  @param logicalIndex - the logical index of the row that has been
         *      changed
         *  @param oldSize - int containing the old size in number of pixels
         *  @param newSize - int containing the new size in number of pixels
         */
        void updateSectionHeight(int logicalIndex, int oldSize, int newSize);

    signals:
        /**
         *  Signal that contains a search query.
         *  Use it by connecting it to your data model's search implementation
         *
         *  @param searchQuery - QList of QVariants containing the search query
         */
        void boxQuery(const QList<QVariant> searchQuery);

        /**
         *  Signal that is thrown when when one of the SearchTableDelegate
         *  icons was clicked.
         *  Use it by connecting it to your data model's function of choice
         *
         *   @param index - index whose button was clicked
         */
        void buttonClicked(const QModelIndex &index);
    };
}
#endif